const createAuthor = (author) => {
  const name =
    typeof author === "string" ? author : author.name ?? author.id ?? "system";
  const id =
    typeof author === "string" ? author : author.id ?? author.name ?? "system";

  return {
    create_name: name,
    create_id: id,
    modify_name: name,
    modify_id: id,
  };
};

const adminAuthor = createAuthor("admin");
const allSkip = true;

const insertData = [
  {
    name: "company",
    modelName: "company",
    schemaName: "Company",
    skip: allSkip ?? true,
    data: [{ id: "none", name: "holder for no company" }],
    destroy: false,
  },
  {
    name: "user",
    modelName: "user",
    schemaName: "User",
    skip: allSkip ?? true,
    data: [
      {
        user_type: 0,
        company_id: "none",
        account: "admin",
        name: "admin",
        password: "123456",
      },
    ],
    destroy: false,
  },
  {
    name: "country",
    modelName: "country",
    schemaName: "Country",
    skip: allSkip ?? true,
    data: [{ id: "none", name: "holder for no country" }],
    destroy: false,
  },
  {
    name: "stock_brand",
    modelName: "stock_brand",
    schemaName: "StockBrand",
    skip: allSkip ?? true,
    data: [
      {
        name: "default insert brand",
        company_id: "none",
      },
    ],
    destroy: false,
  },
  {
    name: "stock_accounting",
    modelName: "stock_accounting",
    schemaName: "StockAccounting",
    skip: allSkip ?? true,
    data: [
      {
        name: "default insert x",
        code: "x001",
        company_id: "none",
      },
      {
        name: "default insert y",
        code: "y001",
        company_id: "none",
      },
    ],
    destroy: false,
  },
  {
    name: "member_level",
    modelName: "member_level",
    schemaName: "MemberLevel",
    skip: allSkip ?? true,
    data: [
      {
        id: "level_A",
        name: "A",
      },
      {
        id: "level_B",
        name: "B",
      },
      {
        id: "level_C",
        name: "C",
      },
      {
        id: "level_D",
        name: "D",
      },
      {
        id: "level_E",
        name: "E",
      },
    ],
    destroy: true,
  },
  {
    name: "member_role",
    modelName: "member_role",
    schemaName: "MemberRole",
    skip: allSkip ?? true,
    data: [
      {
        id: "normal",
        name: "一般",
      },
      {
        id: "distributor",
        name: "經銷商",
      },
    ],
    destroy: true,
  },
  {
    name: "member_shipping",
    modelName: "member_shipping",
    schemaName: "MemberShipping",
    skip: allSkip ?? true,
    data: [
      {
        id: "uuid_placeholder",
        name: "di_normal",
      },
      {
        id: "uuid_placeholder",
        name: "di_fast",
      },
    ],
    destroy: false,
  },
  {
    name: "payment_method",
    modelName: "payment",
    schemaName: "Payment",
    skip: allSkip ?? true,
    data: [
      {
        id: "uuid_placeholder",
        name: "現金",
        belong: "supplier",
      },
      {
        id: "uuid_placeholder",
        name: "支票",
        belong: "supplier",
      },
      {
        id: "uuid_placeholder",
        name: "匯款",
        belong: "supplier",
      },
    ],
    destroy: false,
    author: adminAuthor,
  },
  {
    name: "account_method",
    modelName: "account_method",
    schemaName: "AccountMethod",
    skip: allSkip ?? true,
    data: [
      {
        name: "日結",
      },
      {
        name: "周結",
      },
      {
        name: "月結",
      },
      {
        name: "出貨前付款",
      },
    ],
    destroy: false,
    author: adminAuthor,
  },
  {
    name: "delivery",
    modelName: "delivery",
    schemaName: "Delivery",
    skip: allSkip ?? true,
    data: [
      {
        id: "board",
        name: "板出",
        code: "board",
        delivery_type_id: "none",
      },
      {
        id: "home",
        name: "宅配",
        code: "home",
        delivery_type_id: "none",
      },
    ],
    destroy: false,
    author: adminAuthor,
  },
  {
    name: "county",
    modelName: "county",
    schemaName: "County",
    skip: allSkip ?? true,
    data: [
      {
        id: 1,
        county: "台北市",
        zip: "100",
        district: "中正區",
        description: null,
      },
      {
        id: 2,
        county: "台北市",
        zip: "103",
        district: "大同區",
        description: null,
      },
      {
        id: 3,
        county: "台北市",
        zip: "104",
        district: "中山區",
        description: null,
      },
      {
        id: 4,
        county: "台北市",
        zip: "105",
        district: "松山區",
        description: null,
      },
      {
        id: 5,
        county: "台北市",
        zip: "106",
        district: "大安區",
        description: null,
      },
      {
        id: 6,
        county: "台北市",
        zip: "108",
        district: "萬華區",
        description: null,
      },
      {
        id: 7,
        county: "台北市",
        zip: "110",
        district: "信義區",
        description: null,
      },
      {
        id: 8,
        county: "台北市",
        zip: "111",
        district: "士林區",
        description: null,
      },
      {
        id: 9,
        county: "台北市",
        zip: "112",
        district: "北投區",
        description: null,
      },
      {
        id: 10,
        county: "台北市",
        zip: "114",
        district: "內湖區",
        description: null,
      },
      {
        id: 11,
        county: "台北市",
        zip: "115",
        district: "南港區",
        description: null,
      },
      {
        id: 12,
        county: "台北市",
        zip: "116",
        district: "文山區",
        description: null,
      },
      {
        id: 13,
        county: "基隆市",
        zip: "200",
        district: "仁愛區",
        description: null,
      },
      {
        id: 14,
        county: "基隆市",
        zip: "201",
        district: "信義區",
        description: null,
      },
      {
        id: 15,
        county: "基隆市",
        zip: "202",
        district: "中正區",
        description: null,
      },
      {
        id: 16,
        county: "基隆市",
        zip: "203",
        district: "中山區",
        description: null,
      },
      {
        id: 17,
        county: "基隆市",
        zip: "204",
        district: "安樂區",
        description: null,
      },
      {
        id: 18,
        county: "基隆市",
        zip: "205",
        district: "暖暖區",
        description: null,
      },
      {
        id: 19,
        county: "基隆市",
        zip: "206",
        district: "七堵區",
        description: null,
      },
      {
        id: 20,
        county: "新北市",
        zip: "207",
        district: "萬里區",
        description: null,
      },
      {
        id: 21,
        county: "新北市",
        zip: "208",
        district: "金山區",
        description: null,
      },
      {
        id: 22,
        county: "新北市",
        zip: "220",
        district: "板橋區",
        description: null,
      },
      {
        id: 23,
        county: "新北市",
        zip: "221",
        district: "汐止區",
        description: null,
      },
      {
        id: 24,
        county: "新北市",
        zip: "222",
        district: "深坑區",
        description: null,
      },
      {
        id: 25,
        county: "新北市",
        zip: "223",
        district: "石碇區",
        description: null,
      },
      {
        id: 26,
        county: "新北市",
        zip: "224",
        district: "瑞芳區",
        description: null,
      },
      {
        id: 27,
        county: "新北市",
        zip: "226",
        district: "平溪區",
        description: null,
      },
      {
        id: 28,
        county: "新北市",
        zip: "227",
        district: "雙溪區",
        description: null,
      },
      {
        id: 29,
        county: "新北市",
        zip: "228",
        district: "貢寮區",
        description: null,
      },
      {
        id: 30,
        county: "新北市",
        zip: "231",
        district: "新店區",
        description: null,
      },
      {
        id: 31,
        county: "新北市",
        zip: "232",
        district: "坪林區",
        description: null,
      },
      {
        id: 32,
        county: "新北市",
        zip: "233",
        district: "烏來區",
        description: null,
      },
      {
        id: 33,
        county: "新北市",
        zip: "234",
        district: "永和區",
        description: null,
      },
      {
        id: 34,
        county: "新北市",
        zip: "235",
        district: "中和區",
        description: null,
      },
      {
        id: 35,
        county: "新北市",
        zip: "236",
        district: "土城區",
        description: null,
      },
      {
        id: 36,
        county: "新北市",
        zip: "237",
        district: "三峽區",
        description: null,
      },
      {
        id: 37,
        county: "新北市",
        zip: "238",
        district: "樹林區",
        description: null,
      },
      {
        id: 38,
        county: "新北市",
        zip: "239",
        district: "鶯歌區",
        description: null,
      },
      {
        id: 39,
        county: "新北市",
        zip: "241",
        district: "三重區",
        description: null,
      },
      {
        id: 40,
        county: "新北市",
        zip: "242",
        district: "新莊區",
        description: null,
      },
      {
        id: 41,
        county: "新北市",
        zip: "243",
        district: "泰山區",
        description: null,
      },
      {
        id: 42,
        county: "新北市",
        zip: "244",
        district: "林口區",
        description: null,
      },
      {
        id: 43,
        county: "新北市",
        zip: "247",
        district: "蘆洲區",
        description: null,
      },
      {
        id: 44,
        county: "新北市",
        zip: "248",
        district: "五股區",
        description: null,
      },
      {
        id: 45,
        county: "新北市",
        zip: "249",
        district: "八里區",
        description: null,
      },
      {
        id: 46,
        county: "新北市",
        zip: "251",
        district: "淡水區",
        description: null,
      },
      {
        id: 47,
        county: "新北市",
        zip: "252",
        district: "三芝區",
        description: null,
      },
      {
        id: 48,
        county: "新北市",
        zip: "253",
        district: "石門區",
        description: null,
      },
      {
        id: 49,
        county: "宜蘭縣",
        zip: "260",
        district: "宜蘭市",
        description: null,
      },
      {
        id: 50,
        county: "宜蘭縣",
        zip: "261",
        district: "頭城鎮",
        description: null,
      },
      {
        id: 51,
        county: "宜蘭縣",
        zip: "262",
        district: "礁溪鄉",
        description: null,
      },
      {
        id: 52,
        county: "宜蘭縣",
        zip: "263",
        district: "壯圍鄉",
        description: null,
      },
      {
        id: 53,
        county: "宜蘭縣",
        zip: "264",
        district: "員山鄉",
        description: null,
      },
      {
        id: 54,
        county: "宜蘭縣",
        zip: "265",
        district: "羅東鎮",
        description: null,
      },
      {
        id: 55,
        county: "宜蘭縣",
        zip: "266",
        district: "三星鄉",
        description: null,
      },
      {
        id: 56,
        county: "宜蘭縣",
        zip: "267",
        district: "大同鄉",
        description: null,
      },
      {
        id: 57,
        county: "宜蘭縣",
        zip: "268",
        district: "五結鄉",
        description: null,
      },
      {
        id: 58,
        county: "宜蘭縣",
        zip: "269",
        district: "冬山鄉",
        description: null,
      },
      {
        id: 59,
        county: "宜蘭縣",
        zip: "270",
        district: "蘇澳鎮",
        description: null,
      },
      {
        id: 60,
        county: "宜蘭縣",
        zip: "272",
        district: "南澳鄉",
        description: null,
      },
      {
        id: 61,
        county: "宜蘭縣",
        zip: "290",
        district: "釣魚台列嶼",
        description: null,
      },
      {
        id: 62,
        county: "桃園市",
        zip: "320",
        district: "中壢區",
        description: null,
      },
      {
        id: 63,
        county: "桃園市",
        zip: "324",
        district: "平鎮區",
        description: null,
      },
      {
        id: 64,
        county: "桃園市",
        zip: "325",
        district: "龍潭區",
        description: null,
      },
      {
        id: 65,
        county: "桃園市",
        zip: "326",
        district: "楊梅區",
        description: null,
      },
      {
        id: 66,
        county: "桃園市",
        zip: "327",
        district: "新屋區",
        description: null,
      },
      {
        id: 67,
        county: "桃園市",
        zip: "328",
        district: "觀音區",
        description: null,
      },
      {
        id: 68,
        county: "桃園市",
        zip: "330",
        district: "桃園區",
        description: null,
      },
      {
        id: 69,
        county: "桃園市",
        zip: "333",
        district: "龜山區",
        description: null,
      },
      {
        id: 70,
        county: "桃園市",
        zip: "334",
        district: "八德區",
        description: null,
      },
      {
        id: 71,
        county: "桃園市",
        zip: "335",
        district: "大溪區",
        description: null,
      },
      {
        id: 72,
        county: "桃園市",
        zip: "336",
        district: "復興區",
        description: null,
      },
      {
        id: 73,
        county: "桃園市",
        zip: "337",
        district: "大園區",
        description: null,
      },
      {
        id: 74,
        county: "桃園市",
        zip: "338",
        district: "蘆竹區",
        description: null,
      },
      {
        id: 75,
        county: "新竹市",
        zip: "300",
        district: "東區",
        description: null,
      },
      {
        id: 76,
        county: "新竹市",
        zip: "300",
        district: "北區",
        description: null,
      },
      {
        id: 77,
        county: "新竹市",
        zip: "300",
        district: "香山區",
        description: null,
      },
      {
        id: 78,
        county: "新竹縣",
        zip: "302",
        district: "竹北市",
        description: null,
      },
      {
        id: 79,
        county: "新竹縣",
        zip: "303",
        district: "湖口鄉",
        description: null,
      },
      {
        id: 80,
        county: "新竹縣",
        zip: "304",
        district: "新豐鄉",
        description: null,
      },
      {
        id: 81,
        county: "新竹縣",
        zip: "305",
        district: "新埔鎮",
        description: null,
      },
      {
        id: 82,
        county: "新竹縣",
        zip: "306",
        district: "關西鎮",
        description: null,
      },
      {
        id: 83,
        county: "新竹縣",
        zip: "307",
        district: "芎林鄉",
        description: null,
      },
      {
        id: 84,
        county: "新竹縣",
        zip: "308",
        district: "寶山鄉",
        description: null,
      },
      {
        id: 85,
        county: "新竹縣",
        zip: "310",
        district: "竹東鎮",
        description: null,
      },
      {
        id: 86,
        county: "新竹縣",
        zip: "311",
        district: "五峰鄉",
        description: null,
      },
      {
        id: 87,
        county: "新竹縣",
        zip: "312",
        district: "橫山鄉",
        description: null,
      },
      {
        id: 88,
        county: "新竹縣",
        zip: "313",
        district: "尖石鄉",
        description: null,
      },
      {
        id: 89,
        county: "新竹縣",
        zip: "314",
        district: "北埔鄉",
        description: null,
      },
      {
        id: 90,
        county: "新竹縣",
        zip: "315",
        district: "峨眉鄉",
        description: null,
      },
      {
        id: 91,
        county: "苗栗縣",
        zip: "350",
        district: "竹南鎮",
        description: null,
      },
      {
        id: 92,
        county: "苗栗縣",
        zip: "351",
        district: "頭份市",
        description: null,
      },
      {
        id: 93,
        county: "苗栗縣",
        zip: "352",
        district: "三灣鄉",
        description: null,
      },
      {
        id: 94,
        county: "苗栗縣",
        zip: "353",
        district: "南庄鄉",
        description: null,
      },
      {
        id: 95,
        county: "苗栗縣",
        zip: "354",
        district: "獅潭鄉",
        description: null,
      },
      {
        id: 96,
        county: "苗栗縣",
        zip: "356",
        district: "後龍鎮",
        description: null,
      },
      {
        id: 97,
        county: "苗栗縣",
        zip: "357",
        district: "通霄鎮",
        description: null,
      },
      {
        id: 98,
        county: "苗栗縣",
        zip: "358",
        district: "苑裡鎮",
        description: null,
      },
      {
        id: 99,
        county: "苗栗縣",
        zip: "360",
        district: "苗栗市",
        description: null,
      },
      {
        id: 100,
        county: "苗栗縣",
        zip: "361",
        district: "造橋鄉",
        description: null,
      },
      {
        id: 101,
        county: "苗栗縣",
        zip: "362",
        district: "頭屋鄉",
        description: null,
      },
      {
        id: 102,
        county: "苗栗縣",
        zip: "363",
        district: "公館鄉",
        description: null,
      },
      {
        id: 103,
        county: "苗栗縣",
        zip: "364",
        district: "大湖鄉",
        description: null,
      },
      {
        id: 104,
        county: "苗栗縣",
        zip: "365",
        district: "泰安鄉",
        description: null,
      },
      {
        id: 105,
        county: "苗栗縣",
        zip: "366",
        district: "銅鑼鄉",
        description: null,
      },
      {
        id: 106,
        county: "苗栗縣",
        zip: "367",
        district: "三義鄉",
        description: null,
      },
      {
        id: 107,
        county: "苗栗縣",
        zip: "368",
        district: "西湖鄉",
        description: null,
      },
      {
        id: 108,
        county: "苗栗縣",
        zip: "369",
        district: "卓蘭鎮",
        description: null,
      },
      {
        id: 109,
        county: "台中市",
        zip: "400",
        district: "中區",
        description: null,
      },
      {
        id: 110,
        county: "台中市",
        zip: "401",
        district: "東區",
        description: null,
      },
      {
        id: 111,
        county: "台中市",
        zip: "402",
        district: "南區",
        description: null,
      },
      {
        id: 112,
        county: "台中市",
        zip: "403",
        district: "西區",
        description: null,
      },
      {
        id: 113,
        county: "台中市",
        zip: "404",
        district: "北區",
        description: null,
      },
      {
        id: 114,
        county: "台中市",
        zip: "406",
        district: "北屯區",
        description: null,
      },
      {
        id: 115,
        county: "台中市",
        zip: "407",
        district: "西屯區",
        description: null,
      },
      {
        id: 116,
        county: "台中市",
        zip: "408",
        district: "南屯區",
        description: null,
      },
      {
        id: 117,
        county: "台中市",
        zip: "411",
        district: "太平區",
        description: null,
      },
      {
        id: 118,
        county: "台中市",
        zip: "412",
        district: "大里區",
        description: null,
      },
      {
        id: 119,
        county: "台中市",
        zip: "413",
        district: "霧峰區",
        description: null,
      },
      {
        id: 120,
        county: "台中市",
        zip: "414",
        district: "烏日區",
        description: null,
      },
      {
        id: 121,
        county: "台中市",
        zip: "420",
        district: "豐原區",
        description: null,
      },
      {
        id: 122,
        county: "台中市",
        zip: "421",
        district: "后里區",
        description: null,
      },
      {
        id: 123,
        county: "台中市",
        zip: "422",
        district: "石岡區",
        description: null,
      },
      {
        id: 124,
        county: "台中市",
        zip: "423",
        district: "東勢區",
        description: null,
      },
      {
        id: 125,
        county: "台中市",
        zip: "424",
        district: "和平區",
        description: null,
      },
      {
        id: 126,
        county: "台中市",
        zip: "426",
        district: "新社區",
        description: null,
      },
      {
        id: 127,
        county: "台中市",
        zip: "427",
        district: "潭子區",
        description: null,
      },
      {
        id: 128,
        county: "台中市",
        zip: "428",
        district: "大雅區",
        description: null,
      },
      {
        id: 129,
        county: "台中市",
        zip: "429",
        district: "神岡區",
        description: null,
      },
      {
        id: 130,
        county: "台中市",
        zip: "432",
        district: "大肚區",
        description: null,
      },
      {
        id: 131,
        county: "台中市",
        zip: "433",
        district: "沙鹿區",
        description: null,
      },
      {
        id: 132,
        county: "台中市",
        zip: "434",
        district: "龍井區",
        description: null,
      },
      {
        id: 133,
        county: "台中市",
        zip: "435",
        district: "梧棲區",
        description: null,
      },
      {
        id: 134,
        county: "台中市",
        zip: "436",
        district: "清水區",
        description: null,
      },
      {
        id: 135,
        county: "台中市",
        zip: "437",
        district: "大甲區",
        description: null,
      },
      {
        id: 136,
        county: "台中市",
        zip: "438",
        district: "外埔區",
        description: null,
      },
      {
        id: 137,
        county: "台中市",
        zip: "439",
        district: "大安區",
        description: null,
      },
      {
        id: 138,
        county: "彰化縣",
        zip: "500",
        district: "彰化市",
        description: null,
      },
      {
        id: 139,
        county: "彰化縣",
        zip: "502",
        district: "芬園鄉",
        description: null,
      },
      {
        id: 140,
        county: "彰化縣",
        zip: "503",
        district: "花壇鄉",
        description: null,
      },
      {
        id: 141,
        county: "彰化縣",
        zip: "504",
        district: "秀水鄉",
        description: null,
      },
      {
        id: 142,
        county: "彰化縣",
        zip: "505",
        district: "鹿港鎮",
        description: null,
      },
      {
        id: 143,
        county: "彰化縣",
        zip: "506",
        district: "福興鄉",
        description: null,
      },
      {
        id: 144,
        county: "彰化縣",
        zip: "507",
        district: "線西鄉",
        description: null,
      },
      {
        id: 145,
        county: "彰化縣",
        zip: "508",
        district: "和美鎮",
        description: null,
      },
      {
        id: 146,
        county: "彰化縣",
        zip: "509",
        district: "伸港鄉",
        description: null,
      },
      {
        id: 147,
        county: "彰化縣",
        zip: "510",
        district: "員林市",
        description: null,
      },
      {
        id: 148,
        county: "彰化縣",
        zip: "511",
        district: "社頭鄉",
        description: null,
      },
      {
        id: 149,
        county: "彰化縣",
        zip: "512",
        district: "永靖鄉",
        description: null,
      },
      {
        id: 150,
        county: "彰化縣",
        zip: "513",
        district: "埔心鄉",
        description: null,
      },
      {
        id: 151,
        county: "彰化縣",
        zip: "514",
        district: "溪湖鎮",
        description: null,
      },
      {
        id: 152,
        county: "彰化縣",
        zip: "515",
        district: "大村鄉",
        description: null,
      },
      {
        id: 153,
        county: "彰化縣",
        zip: "516",
        district: "埔鹽鄉",
        description: null,
      },
      {
        id: 154,
        county: "彰化縣",
        zip: "520",
        district: "田中鎮",
        description: null,
      },
      {
        id: 155,
        county: "彰化縣",
        zip: "521",
        district: "北斗鎮",
        description: null,
      },
      {
        id: 156,
        county: "彰化縣",
        zip: "522",
        district: "田尾鄉",
        description: null,
      },
      {
        id: 157,
        county: "彰化縣",
        zip: "523",
        district: "埤頭鄉",
        description: null,
      },
      {
        id: 158,
        county: "彰化縣",
        zip: "524",
        district: "溪州鄉",
        description: null,
      },
      {
        id: 159,
        county: "彰化縣",
        zip: "525",
        district: "竹塘鄉",
        description: null,
      },
      {
        id: 160,
        county: "彰化縣",
        zip: "526",
        district: "二林鎮",
        description: null,
      },
      {
        id: 161,
        county: "彰化縣",
        zip: "527",
        district: "大城鄉",
        description: null,
      },
      {
        id: 162,
        county: "彰化縣",
        zip: "528",
        district: "芳苑鄉",
        description: null,
      },
      {
        id: 163,
        county: "彰化縣",
        zip: "530",
        district: "二水鄉",
        description: null,
      },
      {
        id: 164,
        county: "南投縣",
        zip: "540",
        district: "南投市",
        description: null,
      },
      {
        id: 165,
        county: "南投縣",
        zip: "541",
        district: "中寮鄉",
        description: null,
      },
      {
        id: 166,
        county: "南投縣",
        zip: "542",
        district: "草屯鎮",
        description: null,
      },
      {
        id: 167,
        county: "南投縣",
        zip: "544",
        district: "國姓鄉",
        description: null,
      },
      {
        id: 168,
        county: "南投縣",
        zip: "545",
        district: "埔里鎮",
        description: null,
      },
      {
        id: 169,
        county: "南投縣",
        zip: "546",
        district: "仁愛鄉",
        description: null,
      },
      {
        id: 170,
        county: "南投縣",
        zip: "551",
        district: "名間鄉",
        description: null,
      },
      {
        id: 171,
        county: "南投縣",
        zip: "552",
        district: "集集鎮",
        description: null,
      },
      {
        id: 172,
        county: "南投縣",
        zip: "553",
        district: "水里鄉",
        description: null,
      },
      {
        id: 173,
        county: "南投縣",
        zip: "555",
        district: "魚池鄉",
        description: null,
      },
      {
        id: 174,
        county: "南投縣",
        zip: "556",
        district: "信義鄉",
        description: null,
      },
      {
        id: 175,
        county: "南投縣",
        zip: "557",
        district: "竹山鎮",
        description: null,
      },
      {
        id: 176,
        county: "南投縣",
        zip: "558",
        district: "鹿谷鄉",
        description: null,
      },
      {
        id: 177,
        county: "嘉義市",
        zip: "600",
        district: "東區",
        description: null,
      },
      {
        id: 178,
        county: "嘉義市",
        zip: "600",
        district: "西區",
        description: null,
      },
      {
        id: 179,
        county: "嘉義縣",
        zip: "602",
        district: "番路鄉",
        description: null,
      },
      {
        id: 180,
        county: "嘉義縣",
        zip: "603",
        district: "梅山鄉",
        description: null,
      },
      {
        id: 181,
        county: "嘉義縣",
        zip: "604",
        district: "竹崎鄉",
        description: null,
      },
      {
        id: 182,
        county: "嘉義縣",
        zip: "605",
        district: "阿里山",
        description: null,
      },
      {
        id: 183,
        county: "嘉義縣",
        zip: "606",
        district: "中埔鄉",
        description: null,
      },
      {
        id: 184,
        county: "嘉義縣",
        zip: "607",
        district: "大埔鄉",
        description: null,
      },
      {
        id: 185,
        county: "嘉義縣",
        zip: "608",
        district: "水上鄉",
        description: null,
      },
      {
        id: 186,
        county: "嘉義縣",
        zip: "611",
        district: "鹿草鄉",
        description: null,
      },
      {
        id: 187,
        county: "嘉義縣",
        zip: "612",
        district: "太保市",
        description: null,
      },
      {
        id: 188,
        county: "嘉義縣",
        zip: "613",
        district: "朴子市",
        description: null,
      },
      {
        id: 189,
        county: "嘉義縣",
        zip: "614",
        district: "東石鄉",
        description: null,
      },
      {
        id: 190,
        county: "嘉義縣",
        zip: "615",
        district: "六腳鄉",
        description: null,
      },
      {
        id: 191,
        county: "嘉義縣",
        zip: "616",
        district: "新港鄉",
        description: null,
      },
      {
        id: 192,
        county: "嘉義縣",
        zip: "621",
        district: "民雄鄉",
        description: null,
      },
      {
        id: 193,
        county: "嘉義縣",
        zip: "622",
        district: "大林鎮",
        description: null,
      },
      {
        id: 194,
        county: "嘉義縣",
        zip: "623",
        district: "溪口鄉",
        description: null,
      },
      {
        id: 195,
        county: "嘉義縣",
        zip: "624",
        district: "義竹鄉",
        description: null,
      },
      {
        id: 196,
        county: "嘉義縣",
        zip: "625",
        district: "布袋鎮",
        description: null,
      },
      {
        id: 197,
        county: "雲林縣",
        zip: "630",
        district: "斗南鎮",
        description: null,
      },
      {
        id: 198,
        county: "雲林縣",
        zip: "631",
        district: "大埤鄉",
        description: null,
      },
      {
        id: 199,
        county: "雲林縣",
        zip: "632",
        district: "虎尾鎮",
        description: null,
      },
      {
        id: 200,
        county: "雲林縣",
        zip: "633",
        district: "土庫鎮",
        description: null,
      },
      {
        id: 201,
        county: "雲林縣",
        zip: "634",
        district: "褒忠鄉",
        description: null,
      },
      {
        id: 202,
        county: "雲林縣",
        zip: "635",
        district: "東勢鄉",
        description: null,
      },
      {
        id: 203,
        county: "雲林縣",
        zip: "636",
        district: "台西鄉",
        description: null,
      },
      {
        id: 204,
        county: "雲林縣",
        zip: "637",
        district: "崙背鄉",
        description: null,
      },
      {
        id: 205,
        county: "雲林縣",
        zip: "638",
        district: "麥寮鄉",
        description: null,
      },
      {
        id: 206,
        county: "雲林縣",
        zip: "640",
        district: "斗六市",
        description: null,
      },
      {
        id: 207,
        county: "雲林縣",
        zip: "643",
        district: "林內鄉",
        description: null,
      },
      {
        id: 208,
        county: "雲林縣",
        zip: "646",
        district: "古坑鄉",
        description: null,
      },
      {
        id: 209,
        county: "雲林縣",
        zip: "647",
        district: "莿桐鄉",
        description: null,
      },
      {
        id: 210,
        county: "雲林縣",
        zip: "648",
        district: "西螺鎮",
        description: null,
      },
      {
        id: 211,
        county: "雲林縣",
        zip: "649",
        district: "二崙鄉",
        description: null,
      },
      {
        id: 212,
        county: "雲林縣",
        zip: "651",
        district: "北港鎮",
        description: null,
      },
      {
        id: 213,
        county: "雲林縣",
        zip: "652",
        district: "水林鄉",
        description: null,
      },
      {
        id: 214,
        county: "雲林縣",
        zip: "653",
        district: "口湖鄉",
        description: null,
      },
      {
        id: 215,
        county: "雲林縣",
        zip: "654",
        district: "四湖鄉",
        description: null,
      },
      {
        id: 216,
        county: "雲林縣",
        zip: "655",
        district: "元長鄉",
        description: null,
      },
      {
        id: 217,
        county: "台南市",
        zip: "700",
        district: "中西區",
        description: null,
      },
      {
        id: 218,
        county: "台南市",
        zip: "701",
        district: "東區",
        description: null,
      },
      {
        id: 219,
        county: "台南市",
        zip: "702",
        district: "南區",
        description: null,
      },
      {
        id: 220,
        county: "台南市",
        zip: "704",
        district: "北區",
        description: null,
      },
      {
        id: 221,
        county: "台南市",
        zip: "708",
        district: "安平區",
        description: null,
      },
      {
        id: 222,
        county: "台南市",
        zip: "709",
        district: "安南區",
        description: null,
      },
      {
        id: 223,
        county: "台南市",
        zip: "710",
        district: "永康區",
        description: null,
      },
      {
        id: 224,
        county: "台南市",
        zip: "711",
        district: "歸仁區",
        description: null,
      },
      {
        id: 225,
        county: "台南市",
        zip: "712",
        district: "新化區",
        description: null,
      },
      {
        id: 226,
        county: "台南市",
        zip: "713",
        district: "左鎮區",
        description: null,
      },
      {
        id: 227,
        county: "台南市",
        zip: "714",
        district: "玉井區",
        description: null,
      },
      {
        id: 228,
        county: "台南市",
        zip: "715",
        district: "楠西區",
        description: null,
      },
      {
        id: 229,
        county: "台南市",
        zip: "716",
        district: "南化區",
        description: null,
      },
      {
        id: 230,
        county: "台南市",
        zip: "717",
        district: "仁德區",
        description: null,
      },
      {
        id: 231,
        county: "台南市",
        zip: "718",
        district: "關廟區",
        description: null,
      },
      {
        id: 232,
        county: "台南市",
        zip: "719",
        district: "龍崎區",
        description: null,
      },
      {
        id: 233,
        county: "台南市",
        zip: "720",
        district: "官田區",
        description: null,
      },
      {
        id: 234,
        county: "台南市",
        zip: "721",
        district: "麻豆區",
        description: null,
      },
      {
        id: 235,
        county: "台南市",
        zip: "722",
        district: "佳里區",
        description: null,
      },
      {
        id: 236,
        county: "台南市",
        zip: "723",
        district: "西港區",
        description: null,
      },
      {
        id: 237,
        county: "台南市",
        zip: "724",
        district: "七股區",
        description: null,
      },
      {
        id: 238,
        county: "台南市",
        zip: "725",
        district: "將軍區",
        description: null,
      },
      {
        id: 239,
        county: "台南市",
        zip: "726",
        district: "學甲區",
        description: null,
      },
      {
        id: 240,
        county: "台南市",
        zip: "727",
        district: "北門區",
        description: null,
      },
      {
        id: 241,
        county: "台南市",
        zip: "730",
        district: "新營區",
        description: null,
      },
      {
        id: 242,
        county: "台南市",
        zip: "731",
        district: "後壁區",
        description: null,
      },
      {
        id: 243,
        county: "台南市",
        zip: "732",
        district: "白河區",
        description: null,
      },
      {
        id: 244,
        county: "台南市",
        zip: "733",
        district: "東山區",
        description: null,
      },
      {
        id: 245,
        county: "台南市",
        zip: "734",
        district: "六甲區",
        description: null,
      },
      {
        id: 246,
        county: "台南市",
        zip: "735",
        district: "下營區",
        description: null,
      },
      {
        id: 247,
        county: "台南市",
        zip: "736",
        district: "柳營區",
        description: null,
      },
      {
        id: 248,
        county: "台南市",
        zip: "737",
        district: "鹽水區",
        description: null,
      },
      {
        id: 249,
        county: "台南市",
        zip: "741",
        district: "善化區",
        description: null,
      },
      {
        id: 250,
        county: "台南市",
        zip: "742",
        district: "大內區",
        description: null,
      },
      {
        id: 251,
        county: "台南市",
        zip: "743",
        district: "山上區",
        description: null,
      },
      {
        id: 252,
        county: "台南市",
        zip: "744",
        district: "新市區",
        description: null,
      },
      {
        id: 253,
        county: "台南市",
        zip: "745",
        district: "安定區",
        description: null,
      },
      {
        id: 254,
        county: "高雄市",
        zip: "800",
        district: "新興區",
        description: null,
      },
      {
        id: 255,
        county: "高雄市",
        zip: "801",
        district: "前金區",
        description: null,
      },
      {
        id: 256,
        county: "高雄市",
        zip: "802",
        district: "苓雅區",
        description: null,
      },
      {
        id: 257,
        county: "高雄市",
        zip: "803",
        district: "鹽埕區",
        description: null,
      },
      {
        id: 258,
        county: "高雄市",
        zip: "804",
        district: "鼓山區",
        description: null,
      },
      {
        id: 259,
        county: "高雄市",
        zip: "805",
        district: "旗津區",
        description: null,
      },
      {
        id: 260,
        county: "高雄市",
        zip: "806",
        district: "前鎮區",
        description: null,
      },
      {
        id: 261,
        county: "高雄市",
        zip: "807",
        district: "三民區",
        description: null,
      },
      {
        id: 262,
        county: "高雄市",
        zip: "811",
        district: "楠梓區",
        description: null,
      },
      {
        id: 263,
        county: "高雄市",
        zip: "812",
        district: "小港區",
        description: null,
      },
      {
        id: 264,
        county: "高雄市",
        zip: "813",
        district: "左營區",
        description: null,
      },
      {
        id: 265,
        county: "高雄市",
        zip: "814",
        district: "仁武區",
        description: null,
      },
      {
        id: 266,
        county: "高雄市",
        zip: "815",
        district: "大社區",
        description: null,
      },
      {
        id: 267,
        county: "高雄市",
        zip: "817",
        district: "東沙群島",
        description: null,
      },
      {
        id: 268,
        county: "高雄市",
        zip: "819",
        district: "南沙群島",
        description: null,
      },
      {
        id: 269,
        county: "高雄市",
        zip: "820",
        district: "岡山區",
        description: null,
      },
      {
        id: 270,
        county: "高雄市",
        zip: "821",
        district: "路竹區",
        description: null,
      },
      {
        id: 271,
        county: "高雄市",
        zip: "822",
        district: "阿蓮區",
        description: null,
      },
      {
        id: 272,
        county: "高雄市",
        zip: "823",
        district: "田寮區",
        description: null,
      },
      {
        id: 273,
        county: "高雄市",
        zip: "824",
        district: "燕巢區",
        description: null,
      },
      {
        id: 274,
        county: "高雄市",
        zip: "825",
        district: "橋頭區",
        description: null,
      },
      {
        id: 275,
        county: "高雄市",
        zip: "826",
        district: "梓官區",
        description: null,
      },
      {
        id: 276,
        county: "高雄市",
        zip: "827",
        district: "彌陀區",
        description: null,
      },
      {
        id: 277,
        county: "高雄市",
        zip: "828",
        district: "永安區",
        description: null,
      },
      {
        id: 278,
        county: "高雄市",
        zip: "829",
        district: "湖內區",
        description: null,
      },
      {
        id: 279,
        county: "高雄市",
        zip: "830",
        district: "鳳山區",
        description: null,
      },
      {
        id: 280,
        county: "高雄市",
        zip: "831",
        district: "大寮區",
        description: null,
      },
      {
        id: 281,
        county: "高雄市",
        zip: "832",
        district: "林園區",
        description: null,
      },
      {
        id: 282,
        county: "高雄市",
        zip: "833",
        district: "鳥松區",
        description: null,
      },
      {
        id: 283,
        county: "高雄市",
        zip: "840",
        district: "大樹區",
        description: null,
      },
      {
        id: 284,
        county: "高雄市",
        zip: "842",
        district: "旗山區",
        description: null,
      },
      {
        id: 285,
        county: "高雄市",
        zip: "843",
        district: "美濃區",
        description: null,
      },
      {
        id: 286,
        county: "高雄市",
        zip: "844",
        district: "六龜區",
        description: null,
      },
      {
        id: 287,
        county: "高雄市",
        zip: "845",
        district: "內門區",
        description: null,
      },
      {
        id: 288,
        county: "高雄市",
        zip: "846",
        district: "杉林區",
        description: null,
      },
      {
        id: 289,
        county: "高雄市",
        zip: "847",
        district: "甲仙區",
        description: null,
      },
      {
        id: 290,
        county: "高雄市",
        zip: "848",
        district: "桃源區",
        description: null,
      },
      {
        id: 291,
        county: "高雄市",
        zip: "849",
        district: "那瑪夏區",
        description: null,
      },
      {
        id: 292,
        county: "高雄市",
        zip: "851",
        district: "茂林區",
        description: null,
      },
      {
        id: 293,
        county: "高雄市",
        zip: "852",
        district: "茄萣區",
        description: null,
      },
      {
        id: 294,
        county: "澎湖縣",
        zip: "880",
        district: "馬公市",
        description: null,
      },
      {
        id: 295,
        county: "澎湖縣",
        zip: "881",
        district: "西嶼鄉",
        description: null,
      },
      {
        id: 296,
        county: "澎湖縣",
        zip: "882",
        district: "望安鄉",
        description: null,
      },
      {
        id: 297,
        county: "澎湖縣",
        zip: "883",
        district: "七美鄉",
        description: null,
      },
      {
        id: 298,
        county: "澎湖縣",
        zip: "884",
        district: "白沙鄉",
        description: null,
      },
      {
        id: 299,
        county: "澎湖縣",
        zip: "885",
        district: "湖西鄉",
        description: null,
      },
      {
        id: 300,
        county: "金門縣",
        zip: "890",
        district: "金沙鎮",
        description: null,
      },
      {
        id: 301,
        county: "金門縣",
        zip: "891",
        district: "金湖鎮",
        description: null,
      },
      {
        id: 302,
        county: "金門縣",
        zip: "892",
        district: "金寧鄉",
        description: null,
      },
      {
        id: 303,
        county: "金門縣",
        zip: "893",
        district: "金城鎮",
        description: null,
      },
      {
        id: 304,
        county: "金門縣",
        zip: "894",
        district: "烈嶼鄉",
        description: null,
      },
      {
        id: 305,
        county: "金門縣",
        zip: "896",
        district: "烏坵鄉",
        description: null,
      },
      {
        id: 306,
        county: "屏東縣",
        zip: "900",
        district: "屏東市",
        description: null,
      },
      {
        id: 307,
        county: "屏東縣",
        zip: "901",
        district: "三地門鄉",
        description: null,
      },
      {
        id: 308,
        county: "屏東縣",
        zip: "902",
        district: "霧台鄉",
        description: null,
      },
      {
        id: 309,
        county: "屏東縣",
        zip: "903",
        district: "瑪家鄉",
        description: null,
      },
      {
        id: 310,
        county: "屏東縣",
        zip: "904",
        district: "九如鄉",
        description: null,
      },
      {
        id: 311,
        county: "屏東縣",
        zip: "905",
        district: "里港鄉",
        description: null,
      },
      {
        id: 312,
        county: "屏東縣",
        zip: "906",
        district: "高樹鄉",
        description: null,
      },
      {
        id: 313,
        county: "屏東縣",
        zip: "907",
        district: "鹽埔鄉",
        description: null,
      },
      {
        id: 314,
        county: "屏東縣",
        zip: "908",
        district: "長治鄉",
        description: null,
      },
      {
        id: 315,
        county: "屏東縣",
        zip: "909",
        district: "麟洛鄉",
        description: null,
      },
      {
        id: 316,
        county: "屏東縣",
        zip: "911",
        district: "竹田鄉",
        description: null,
      },
      {
        id: 317,
        county: "屏東縣",
        zip: "912",
        district: "內埔鄉",
        description: null,
      },
      {
        id: 318,
        county: "屏東縣",
        zip: "913",
        district: "萬丹鄉",
        description: null,
      },
      {
        id: 319,
        county: "屏東縣",
        zip: "920",
        district: "潮州鎮",
        description: null,
      },
      {
        id: 320,
        county: "屏東縣",
        zip: "921",
        district: "泰武鄉",
        description: null,
      },
      {
        id: 321,
        county: "屏東縣",
        zip: "922",
        district: "來義鄉",
        description: null,
      },
      {
        id: 322,
        county: "屏東縣",
        zip: "923",
        district: "萬巒鄉",
        description: null,
      },
      {
        id: 323,
        county: "屏東縣",
        zip: "924",
        district: "崁頂鄉",
        description: null,
      },
      {
        id: 324,
        county: "屏東縣",
        zip: "925",
        district: "新埤鄉",
        description: null,
      },
      {
        id: 325,
        county: "屏東縣",
        zip: "926",
        district: "南州鄉",
        description: null,
      },
      {
        id: 326,
        county: "屏東縣",
        zip: "927",
        district: "林邊鄉",
        description: null,
      },
      {
        id: 327,
        county: "屏東縣",
        zip: "928",
        district: "東港鎮",
        description: null,
      },
      {
        id: 328,
        county: "屏東縣",
        zip: "929",
        district: "琉球鄉",
        description: null,
      },
      {
        id: 329,
        county: "屏東縣",
        zip: "931",
        district: "佳冬鄉",
        description: null,
      },
      {
        id: 330,
        county: "屏東縣",
        zip: "932",
        district: "新園鄉",
        description: null,
      },
      {
        id: 331,
        county: "屏東縣",
        zip: "940",
        district: "枋寮鄉",
        description: null,
      },
      {
        id: 332,
        county: "屏東縣",
        zip: "941",
        district: "枋山鄉",
        description: null,
      },
      {
        id: 333,
        county: "屏東縣",
        zip: "942",
        district: "春日鄉",
        description: null,
      },
      {
        id: 334,
        county: "屏東縣",
        zip: "943",
        district: "獅子鄉",
        description: null,
      },
      {
        id: 335,
        county: "屏東縣",
        zip: "944",
        district: "車城鄉",
        description: null,
      },
      {
        id: 336,
        county: "屏東縣",
        zip: "945",
        district: "牡丹鄉",
        description: null,
      },
      {
        id: 337,
        county: "屏東縣",
        zip: "946",
        district: "恆春鎮",
        description: null,
      },
      {
        id: 338,
        county: "屏東縣",
        zip: "947",
        district: "滿州鄉",
        description: null,
      },
      {
        id: 339,
        county: "台東縣",
        zip: "950",
        district: "台東市",
        description: null,
      },
      {
        id: 340,
        county: "台東縣",
        zip: "951",
        district: "綠島鄉",
        description: null,
      },
      {
        id: 341,
        county: "台東縣",
        zip: "952",
        district: "蘭嶼鄉",
        description: null,
      },
      {
        id: 342,
        county: "台東縣",
        zip: "953",
        district: "延平鄉",
        description: null,
      },
      {
        id: 343,
        county: "台東縣",
        zip: "954",
        district: "卑南鄉",
        description: null,
      },
      {
        id: 344,
        county: "台東縣",
        zip: "955",
        district: "鹿野鄉",
        description: null,
      },
      {
        id: 345,
        county: "台東縣",
        zip: "956",
        district: "關山鎮",
        description: null,
      },
      {
        id: 346,
        county: "台東縣",
        zip: "957",
        district: "海端鄉",
        description: null,
      },
      {
        id: 347,
        county: "台東縣",
        zip: "958",
        district: "池上鄉",
        description: null,
      },
      {
        id: 348,
        county: "台東縣",
        zip: "959",
        district: "東河鄉",
        description: null,
      },
      {
        id: 349,
        county: "台東縣",
        zip: "961",
        district: "成功鎮",
        description: null,
      },
      {
        id: 350,
        county: "台東縣",
        zip: "962",
        district: "長濱鄉",
        description: null,
      },
      {
        id: 351,
        county: "台東縣",
        zip: "963",
        district: "太麻里",
        description: null,
      },
      {
        id: 352,
        county: "台東縣",
        zip: "964",
        district: "金峰鄉",
        description: null,
      },
      {
        id: 353,
        county: "台東縣",
        zip: "965",
        district: "大武鄉",
        description: null,
      },
      {
        id: 354,
        county: "台東縣",
        zip: "966",
        district: "達仁鄉",
        description: null,
      },
      {
        id: 355,
        county: "花蓮縣",
        zip: "970",
        district: "花蓮市",
        description: null,
      },
      {
        id: 356,
        county: "花蓮縣",
        zip: "971",
        district: "新城鄉",
        description: null,
      },
      {
        id: 357,
        county: "花蓮縣",
        zip: "972",
        district: "秀林鄉",
        description: null,
      },
      {
        id: 358,
        county: "花蓮縣",
        zip: "973",
        district: "吉安鄉",
        description: null,
      },
      {
        id: 359,
        county: "花蓮縣",
        zip: "974",
        district: "壽豐鄉",
        description: null,
      },
      {
        id: 360,
        county: "花蓮縣",
        zip: "975",
        district: "鳳林鎮",
        description: null,
      },
      {
        id: 361,
        county: "花蓮縣",
        zip: "976",
        district: "光復鄉",
        description: null,
      },
      {
        id: 362,
        county: "花蓮縣",
        zip: "977",
        district: "豐濱鄉",
        description: null,
      },
      {
        id: 363,
        county: "花蓮縣",
        zip: "978",
        district: "瑞穗鄉",
        description: null,
      },
      {
        id: 364,
        county: "花蓮縣",
        zip: "979",
        district: "萬榮鄉",
        description: null,
      },
      {
        id: 365,
        county: "花蓮縣",
        zip: "981",
        district: "玉里鎮",
        description: null,
      },
      {
        id: 366,
        county: "花蓮縣",
        zip: "982",
        district: "卓溪鄉",
        description: null,
      },
      {
        id: 367,
        county: "花蓮縣",
        zip: "983",
        district: "富里鄉",
        description: null,
      },
      {
        id: 368,
        county: "連江縣",
        zip: "209",
        district: "南竿鄉",
        description: null,
      },
      {
        id: 369,
        county: "連江縣",
        zip: "210",
        district: "北竿鄉",
        description: null,
      },
      {
        id: 370,
        county: "連江縣",
        zip: "211",
        district: "莒光鄉",
        description: null,
      },
      {
        id: 371,
        county: "連江縣",
        zip: "212",
        district: "東引鄉",
        description: null,
      },
    ],
    destroy: false,
  },
];

export default insertData;
